# Generated by Django 2.2 on 2020-11-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('date', models.DateTimeField(blank=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(db_index=True, max_length=50)),
                ('photo', models.ImageField(upload_to='media/img', verbose_name='Фотография пользователя')),
            ],
        ),
    ]
