# Generated by Django 2.2 on 2020-11-03 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=150, verbose_name='Полное имя')),
                ('date', models.DateField(blank=True, verbose_name='Дата рождения')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон')),
                ('email', models.CharField(db_index=True, max_length=50, verbose_name='Электронная почта')),
                ('photo', models.ImageField(upload_to='Image', verbose_name='Фотография')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='Город')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Информация о ползьзователе')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Название')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Номер счета')),
                ('money', models.PositiveIntegerField(default=0, verbose_name='Сумма')),
                ('end_date', models.DateField(blank=True, verbose_name='Дата окончания')),
                ('currency', models.CharField(max_length=30, verbose_name='Валюта')),
                ('bank', models.CharField(max_length=100, verbose_name='Банк')),
                ('bic', models.CharField(max_length=50, verbose_name='БИК')),
                ('inn', models.CharField(max_length=50, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=50, verbose_name='КПП')),
                ('person_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Person', verbose_name='Владелец')),
            ],
        ),
    ]
