# Generated by Django 2.2 on 2020-11-03 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date',
            field=models.DateTimeField(blank=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='person',
            name='full_name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(upload_to='media/img', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=models.SlugField(max_length=150, unique=True, verbose_name='Слаг'),
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Название')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Номер счета')),
                ('money', models.PositiveIntegerField(default=0, verbose_name='Сумма')),
                ('end_date', models.DateTimeField(blank=True, verbose_name='Дата окончания')),
                ('currency', models.CharField(max_length=30, verbose_name='Валюта')),
                ('bank', models.CharField(max_length=100, verbose_name='Банк')),
                ('bic', models.CharField(max_length=50, verbose_name='БИК')),
                ('inn', models.CharField(max_length=50, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=50, verbose_name='КПП')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Person', verbose_name='Владелец')),
            ],
        ),
    ]
