# Generated by Django 2.2 on 2020-11-04 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='adress',
            field=models.CharField(blank=True, max_length=150, verbose_name='Адресс'),
        ),
        migrations.AddField(
            model_name='score',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(default='/Image/no_person.jpg', upload_to='Image', verbose_name='Фотография'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('money', models.PositiveIntegerField(blank=True, verbose_name='Переведенная сумма')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата окончания')),
                ('deposit_score', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deposit', to='home.Score', verbose_name='Счет зачисления')),
                ('write_of_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='write_of', to='home.Score', verbose_name='Счет списания')),
            ],
        ),
    ]
