# Generated by Django 2.2 on 2020-11-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201103_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date',
            field=models.DateField(blank=True, verbose_name='Дата рождения'),
        ),
    ]
