# Generated by Django 2.2 on 2020-11-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201104_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Дата окончания'),
        ),
    ]
