# Generated by Django 2.2 on 2020-11-04 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201104_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='write_of_score',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='write_of', to='home.Score', verbose_name='Счет списания'),
        ),
    ]
