# Generated by Django 2.2 on 2020-11-03 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201103_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='slug',
        ),
    ]
