# Generated by Django 2.2 on 2020-11-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_person_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='end_date',
            field=models.DateField(blank=True, verbose_name='Дата окончания'),
        ),
    ]
