# Generated by Django 2.2 on 2020-11-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201103_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(upload_to='Image', verbose_name='Фотография'),
        ),
    ]
