# Generated by Django 2.2 on 2020-11-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20201103_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='Город'),
        ),
    ]
