# Generated by Django 2.2 on 2020-11-03 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_person_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='person',
            new_name='person_score',
        ),
    ]
